name: ðŸ¥¼ Validate and test apply Station

on:
  workflow_dispatch:
  push:
    branches:
      - 'trunk'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
    tags:
      - '0.*.*'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    environment: Tests
    runs-on: ubuntu-latest
    steps:
    - name: 'Azure: login'
      uses: azure/login@v1
      with:
        client-id:       ${{ secrets.AZ_CLIENT_ID }}
        subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        tenant-id:       ${{ secrets.AZ_TENANT_ID }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: terraform init
      run: terraform init
      working-directory: tests
      env:
        ARM_CLIENT_ID:       ${{ secrets.AZ_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        ARM_TENANT_ID:       ${{ secrets.AZ_TENANT_ID }}
        ARM_USE_OIDC:        true

    - name: terraform plan
      run: terraform plan -out plan.tfplan
      working-directory: tests
      env:
        ARM_CLIENT_ID:       ${{ secrets.AZ_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        ARM_TENANT_ID:       ${{ secrets.AZ_TENANT_ID }}
        ARM_USE_OIDC:        true

